### ISSUE TITLE
Move to GitLab?

### ISSUE THREAD

**Issue by Ma27** [Ma27/rediscala#11]
It seems to be a thing to move repositories to GitLab ATM.
Except the Microsoft deal I really like GitLab CI (currently using it at work) which allows advanced features like custom containers or build outputs. Additionally I **personally** prefer the GitLab UI over GitHub's UI. As many people started moving to GitLab I decided to do this as well with my repos hoping that enough people use `gitlab.com` now, so it becomes *way* more relevant.

@kardapoltsev @herzrasen as you have commit access to this repo, what do you think about this? This is **just** my own opinion, I'll keep my GitHub account for several reasons, so in case you disagree it's absolutely fine to continue working here :-)

**Comment by herzrasen** [comment]
If moving to gitlab has feature advantages compared to github, I wouldn't mind migrating.

**Comment by Ma27** [comment]
> If moving to gitlab has feature advantages compared to github, I wouldn't mind migrating.

:+1: great. I actually prefer GitLab over GitHub. As currently many people move to Gitlab due to recent events, I think that GitLab reaches sufficient popularity to actually use it to host OSS projects.

@kardapoltsev do you agree? I think we should reach consensus about this decision first :)

**Comment by kardapoltsev** [comment]
Hi! Sorry for being so slow (: 
I'm ok with both github or gitlab.

**Comment by Ma27** [comment]
closing now because of two things:

* I don't have the energy to perform the migration ATM, in case GitHub starts to screw things up we can still switch
* GitLab CI isn't as good as at self-hosted GitLab: I managed to get it running on private GitLab instances with fairly powerful machines, but at `gitlab.com` the test suite breaks, as the current setup works quite fine, I'll close it for now
