### ISSUE TITLE
Upgrade to sbt 1.1.1

### ISSUE THREAD

**Issue by herzrasen** [Ma27/rediscala#2]

**Comment by Ma27** [comment]
to avoid some duplicated work here: I started with the upgrade yesterday, however there's quite much breackage. I'll try to fix the packages on the weekend, however we'll also need to find a solution to retain support for SBT 0.13.x users (I lack knowledge about this ATM, but hopefully there's some kind of sbt-cross plugin such as `crossScalaVersions`)

**Comment by Ma27** [comment]
closed as of #4
