### ISSUE TITLE
zrevrangebylex uses max parameter for min

### ISSUE THREAD

**Issue by nickrinaldi** [Ma27/rediscala#20]
This is the definition for zrevrangebylex:

def zrevrangebylex[R: ByteStringDeserializer](key: String, max: Option[String], min: Option[String], limit: Option[(Long, Long)] = None): Future[Seq[R]] =
    send(Zrevrangebylex(key, max.getOrElse("+"), max.getOrElse("-"), limit))

It appears to be using the max parameter for both min and max arguments.

**Comment by kardapoltsev** [comment]
Good catch thanks! Would you like to open PR?
