### ISSUE TITLE
Requests never completed if decoding fails

### ISSUE THREAD

**Issue by dontgitit** [Ma27/rediscala#26]
`Operation` completes its promise with the result of `redisCommand.decodeReply` (in `completeSuccess` and `tryCompleteSuccess`). 
However, if the deserializer throws an exception, it never completes the promise (and I think the thrown exception might cause other issues too). 
This is possible with custom `ByteStringDeserializer` or `RedisReplyDeserializer` that throws in certain scenarios. It's even possible if you try to get something holding an unexpected value, for instance, `set("key", "value")` followed by `get[Double]("key")`. The ActorSystem ends up dumping something like `java.lang.NumberFormatException: For input string: "value"`, but the `Future` returned by `get` never completes. 

Maybe it should be changed to something like:
```scala
  def completeSuccess(redisReply: RedisReplyT): Promise[T] = {
    promise.complete(Try(redisCommand.decodeReply(redisReply)))
  }
  def tryCompleteSuccess(redisReply: RedisReply) = {
    promise.tryComplete(Try(redisCommand.decodeReply(redisReply.asInstanceOf[RedisReplyT])))
  }
```

**Comment by Ma27** [comment]
Thanks a lot for your report! Would you mind filing a patch with your suggested change (and if possible, a testcase or an instruction to reproduce the issue)?
